# Generated by Django 4.2.10 on 2024-03-05 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_blogpost_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='ctitle',
            field=models.CharField(default='', max_length=5000),
        ),
    ]
